### ISSUE TITLE
Error using

### ISSUE THREAD

**Issue by taivu** [roszpun/vue-collapse#1]
`Unhandled rejection Error: Cannot find module 'pug'`

**Comment by taivu** [comment]
should indicate that this component requires PUG for templating

**Comment by roszpun** [comment]
It's not a requirement. You need pug package only when you use PUG instead of normal HTML.

**Comment by roszpun** [comment]
Sorry for that. Plug in now does not require PUG. Update your npm.

**Comment by taivu** [comment]
thanks!!
