### ISSUE TITLE
You made an update yesterday...

### ISSUE THREAD

**Issue by MikeDiehl-CTL** [roszpun/vue-collapse#16]
Had version x.12 now version x.13 and now my menus are not working.

**Comment by Trekels** [comment]
@MikeDiehl-CTL Can you give a more detailled description ?

**Comment by MikeDiehl-CTL** [comment]
fixed the problem by editing the package.json file and pointing "main": back to "src/index.js" not sure what is wrong in the dist/vue-collapsible.js but the none of the v-collapse- directives are working

**Comment by Trekels** [comment]
Seems like the build is not correct, i'll have a look at it and put up a PR asap

**Comment by roszpun** [comment]
Does recent update fix your problem?
