### ISSUE TITLE
Components not being registered anymore

### ISSUE THREAD

**Issue by Flobbos** [roszpun/vue-collapse#17]
I keep getting this error (and many others for all directives and components):

[Vue warn]: Unknown custom element: <v-collapse-wrapper> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 

Although I am following the documentation on how to use collapse:

import VueCollapse from 'vue2-collapse';
Vue.use(VueCollapse);

Running Node 10.4.0 and NPM 6.1.0

Please help, I don't know what to do anymore. Thank you.

**Comment by roszpun** [comment]
Does your application use babel?

**Comment by Grawl** [comment]
still have this problem
