### ISSUE TITLE
render open collapsible

### ISSUE THREAD

**Issue by taivu** [roszpun/vue-collapse#2]
is it possible to allow `wrapper` component to take a `status` prop? i want to render some open and some closed

**Comment by roszpun** [comment]
It is not supported yet, but it's great and simple idea. I will implement it soon.

**Comment by roszpun** [comment]
You can update your npm. Wrapper element can accept `active` property.

Usage:

` <v-collapse-wrapper :active="true"> ... </v-collapse-wrapper>`

Thanks to this you can also bind other logic to this property. This feature will probably replace usage refs for custom triggers.
