### ISSUE TITLE
Error: Can't resolve 'vue-loader'

### ISSUE THREAD

**Issue by binarykiwi** [roszpun/vue-collapse#5]
I've got a setup with Vue2 and webpack up and running. As soon as I install **vue-collapse** via npm
`npm install --save-dev vue2-collapse`
my environment crashes with this error:

```
ERROR in ../node_modules/vue2-collapse/src/index.js
Module not found: Error: Can't resolve 'vue-loader' in [..]
 @ ../node_modules/vue2-collapse/src/index.js 1:0-54 14:48-63
 @ ./js/_app.js
```

As soon as I delete the dependency to **vue-collapse** it is all fine again. For me it seems as something inside **vue-collapse** is buggy.

Do some others have this problem as well?
Or do I have to care about some other things which are not written in the documentation?

Thanks so far.

**Comment by roszpun** [comment]
It looks like a loader problem. Do you have vue-loader installed into your webpack? Plugin uses .vue extension and require vue-loader in order to run.

**Comment by binarykiwi** [comment]
Yes if have vue-loader installed and I use it with other components successfully as well...

**Comment by roszpun** [comment]
Can I see how you import the plugin into your app?

**Comment by binarykiwi** [comment]
Of cause. Like this:
```
import VueCollapse from 'vue2-collapse'
Vue.use(VueCollapse)

```

**Comment by binarykiwi** [comment]
It seems as one of my packages was not in a correct version. After I did an `npm update` now everything seems to work as it should.
