### ISSUE TITLE
Collapse Content max-height problem

### ISSUE THREAD

**Issue by binarykiwi** [roszpun/vue-collapse#6]
I've got an enhancement or maybe it is actually a bug?

The `v-collapse-content` Element gets the CSS class `.v-collapse-content-end` when activated/opend. This class sets a `max-height` of 500px.

```
.v-collapse-content-end {
    transition: max-height 0.3s ease-in;
    max-height: 500px;
}
```

It is not very useful setting a fix max-height. The content inside the `v-collapse-content` Element might be more than 500px of height.

Would be very good getting rid of this so that it works with every content.

**Comment by roszpun** [comment]
I am aware of that. It will be changed in the full release and I will create additional documentation for more complex configuration.

**Comment by abea** [comment]
It doesn't look like this was ever resolved. The package still uses the max-height method set to 500px. If this is still being maintained I suggest this be reopened.
