### ISSUE TITLE
IE 11 error ":" expected

### ISSUE THREAD

**Issue by mksplg** [roszpun/vue-collapse#9]
IE 11 shows an error `":" expected` in [default.js](https://github.com/roszpun/vue-collapse/blob/master/src/defaults.js#L27) as it probably expects an object to have name-value-pairs.

**Comment by roszpun** [comment]
Does @Trekels's commit fix your issue?

**Comment by mksplg** [comment]
Im adding the package to my project via npm so not directly since this still uses the code from `src` directly.

I'm using webpack with babel in my project and by default `node_modules` was excluded. I made an exception for this module and now it works for me.

**Comment by roszpun** [comment]
@Trekels I have updated npm.
